### ISSUE TITLE
カード検索の結果を多い順に表示

### ISSUE THREAD

**Issue by dr-riddles** [iori3150/PTCG-DataBase#53]
採用率が高い順/平均採用枚数が多い順のどっちかで並んでると一番下まで見る必要がなくなる

**Comment by iori3150** [comment]
1枚以上の採用率が高い順に並び替えるので良い？

**Comment by dr-riddles** [comment]
そうだね
その方が簡単かな

2024年4月24日(水) 10:24 Iori Saigo ***@***.***>:
